[project]
name = "fuzzy-logic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo[recommended]>=0.19.8",
    "notebook>=7.5.3",
    "numpy==2.3",
    "pyfuzzy-toolbox[ui]>=1.1.8",
    "scikit-learn>=1.8.0",
]
